import React from 'react'
import { ScrollView, StyleSheet, Text, View } from 'react-native'

const styles = StyleSheet.create({
    item: {
        fontSize:25,
        backgroundColor:'lightblue',
        color:'white',
        margin:5,
        padding:5,
        width:120,
        height:120,
        textAlignVertical:"center",
        textAlign:'center'
    },
    scroll:{
        marginBottom:10,
    }
})

const GridStatic = () => {

    const  users = [
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'tony'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'tony'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'tony'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'tony'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'last'
        },
        {
          id:1,
          name:'Anil'
        },
        {
          id:2,
          name:'shivbhan'
        },
        {
          id:3,
          name:'kushwaha'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'last'
        },
        {
          id:4,
          name:'govind'
        },
        {
          id:5,
          name:'last'
        }
      ]

  return (
    <View>
        <Text style={{fontSize:31}}>Grid with Dynamic Data with scroll</Text>
        <ScrollView style={styles.scroll}>
            <View style={{flex:1,flexDirection:'row',flexWrap:'wrap'}}>
                    {
                        users.map((item) => <Text style={styles.item}>{item.name}</Text>)
                    }
            </View>
        </ScrollView>
    </View>
  )
}

export default GridStatic